name: cfclient
version: git
summary: Crazyflie client
description: |
  Crazyflie client
base: core18
confinement: strict
icon: snap/gui/cfclient.png


parts:
  cfclient:
    plugin: python
    python-version: python3
    source: .

apps:
  cfclient:
    command: python3 -m cfclient.gui
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - raw-usb
      - joystick
